let akashpreet = {
  basics: {
    name: "Akash Preet",
    label: "Full Stack Developer",
    picture: "",
    email: "akash.p96@gmail.com",
    phone: "+91 9750050557",
    website: "",
    summary: "Active Learner, Speaker, Photographer",
    location: {
      address: "6a1, Mani Nagar",
      postalCode: "641305",
      city: "Coimbatore",
      state: "Tamil Nadu",
      stateCode: "TN",
      country: "India",
      countryCode: "IN",
    },
    profiles: [
      {
        network: "Twitter",
        username: "Akash Preet",
        url: "https://twitter.com/akash_preets",
        img: "./assets/logo/twitter.png",
      },
      {
        network: "Facebook",
        username: "Akash Preet",
        url: "https://www.facebook.com/akashpreets",
        img: "./assets/logo/facebook.png",
      },
      {
        network: "LinkedIn",
        username: "Akash P",
        url: "https://www.linkedin.com/in/akashpreet/",
        img: "./assets/logo/linkedin.png",
      },
      {
        network: "Stackoverflow",
        username: "Akash Preet",
        url: "https://stackoverflow.com/users/5678983/akash-preet",
        img: "./assets/logo/stackoverflow.png",
      },
      {
        network: "Github",
        username: "Akash Preet",
        url: "https://github.com/Akash-Preet",
        img: "./assets/logo/github.png",
      },
      {
        network: "Instagram",
        username: "Akash Preet",
        url: "https://www.instagram.com/akash_preets/",
        img: "./assets/logo/instagram.png",
      },
      {
        network: "Email",
        username: "Akash Preet",
        url: "mailto:akash.p96@gmail.com",
        img: "./assets/logo/email.png",
      },
    ],
  },
  work: [
    {
      company: "Company",
      position: "President",
      website: "http://company.com",
      startDate: "2013-01-01",
      endDate: "2014-01-01",
      summary: "Description...",
      highlights: ["Started the company"],
    },
  ],
  volunteer: [
    {
      organization: "Organization",
      position: "Volunteer",
      website: "http://organization.com/",
      startDate: "2012-01-01",
      endDate: "2013-01-01",
      summary: "Description...",
      highlights: ["Awarded 'Volunteer of the Month'"],
    },
  ],
  education: [
    {
      institution: "Jansons Institue Of Technology",
      city: "Coimbatore",
      area: "Computer Science Engineering",
      studyType: "Bachelor",
      startDate: "01-08-2013",
      endDate: "01-05-2017",
      gpa: "7.01",
      percentage: "71",
    },
    {
      institution: "San Jose Matric Hr Sec School",
      city: "Coimbatore",
      area: "Higher Secondary Examination",
      studyType: "XII",
      startDate: "01-06-2012",
      endDate: "01-04-2013",
      gpa: "",
      percentage: "63",
    },
    {
      institution: "San Jose Matric Hr Sec School",
      city: "Coimbatore",
      area: "Secondary School Leaving Certificate Examination",
      studyType: "X",
      startDate: "01-06-2010",
      endDate: "01-05-2011",
      gpa: "",
      percentage: "72",
    },
  ],
  awards: [
    {
      title: "Award",
      date: "2014-11-01",
      awarder: "Company",
      summary: "There is no spoon.",
    },
  ],
  publications: [
    {
      name: "Publication",
      publisher: "Company",
      releaseDate: "2014-10-01",
      website: "http://publication.com",
      summary: "Description...",
    },
  ],
  project: [
    {
      name: "Publication",
      publisher: "Company",
      releaseDate: "2014-10-01",
      website: "http://publication.com",
      summary: "Description...",
    },
  ],
  achivement: [
    {
      name: "Publication",
      publisher: "Company",
      releaseDate: "2014-10-01",
      website: "http://publication.com",
      summary: "Description...",
    },
  ],
  certification: [
    {
      name: "",
      "certified by": "",
      URL: "",
      certificateNo: "",
      summary: "",
    },
  ],
  skills: [
    {
      category: "Front-end",
      keywords: [
        {
          name: "HTML5",
          level: "Master",
          icon: '<i class="devicon-html5-plain"></i>',
          logo: "assets/logo/HTML-5.svg",
        },
        {
          name: "CSS3",
          level: "Master",
          icon: '<i class="devicon-css3-plain"></i>',
          logo: "assets/logo/CSS-3.svg",
        },
        {
          name: "Bootstrap",
          level: "Master",
          icon: '<i class="devicon-bootstrap-plain"></i>',
          logo: "assets/logo/Bootstrap.svg",
        },
        {
          name: "Sass",
          level: "Master",
          icon: '<i class="devicon-sass-plain"></i>',
          logo: "assets/logo/Sass.svg",
        },
        {
          name: "JavaScript",
          level: "Master",
          icon: '<i class="devicon-javascript-plain"></i>',
          logo: "assets/logo/JavaScript.svg",
        },
        {
          name: "TypeScript",
          level: "Master",
          icon: '<i class="devicon-typescript-plain"></i>',
          logo: "assets/logo/Typescript.svg",
        },
        {
          name: "AngularJs",
          level: "Master",
          icon: '<i class="devicon-angularjs-plain"></i>',
          logo: "assets/logo/Angular-JS.svg",
        },
        {
          name: "React",
          level: "Master",
          icon: '<i class="devicon-react-plain"></i>',
          logo: "assets/logo/React.svg",
        },
        {
          name: "VueJs",
          level: "Master",
          icon: '<i class="devicon-vuejs-plain"></i>',
          logo: "assets/logo/Vue-JS.svg",
        },
        {
          name: "Angular",
          level: "Master",
          icon: '<i class="devicon-angularjs-plain"></i>',
          logo: "assets/logo/Angular.svg",
        },
        {
          name: "Quasar Framework",
          level: "Master",
          icon: '<i class="devicon-quasar-plain"></i>',
          logo: "assets/logo/CSS-3.svg",
        },
        {
          name: "SVG",
          level: "Master",
          icon: '<i class="devicon-svg-plain"></i>',
          logo: "assets/logo/SVG.svg",
        },
        {
          name: "D3",
          level: "Master",
          icon: '<i class="devicon-d3js-plain"></i>',
          logo: "assets/logo/SVG.svg",
        },
      ],
    },
    {
      category: "Back-end",
      keywords: [
        {
          name: "C",
          level: "Master",
          icon: '<i class="devicon-c-plain"></i>',
          logo: "assets/logo/C.svg",
        },
        {
          name: "C++",
          level: "Master",
          icon: '<i class="devicon-c-plain"></i>',
          logo: "assets/logo/C++.svg",
        },
        {
          name: "C#",
          level: "Master",
          icon: '<i class="devicon-c-plain"></i>',
          logo: "assets/logo/C-Sharp.svg",
        },
        {
          name: "NodeJs",
          level: "Master",
          icon: '<i class="devicon-nodejs-plain"></i>',
          logo: "assets/logo/node.svg",
        },
        {
          name: "Java",
          level: "Master",
          icon: '<i class="devicon-java-plain"></i>',
          logo: "assets/logo/Java.svg",
        },
        {
          name: "Python",
          level: "Master",
          icon: '<i class="devicon-python-plain"></i>',
          logo: "assets/logo/Python.svg",
        },
        {
          name: "GraphQL",
          level: "Master",
          icon: '<i class="devicon-r-plain"></i>',
          logo: "assets/logo/R-Lang.svg",
        },
        {
          name: "Mongo DB",
          level: "Master",
          icon: '<i class="devicon-mysql-plain"></i>',
          logo: "assets/logo/Mongodb.svg",
        },
        {
          name: "Sql Server",
          level: "Master",
          icon: '<i class="devicon-microsoftsqlserver-plain"></i>',
          logo: "assets/logo/Microsoft-sql-server.svg",
        },
        {
          name: "MySql",
          level: "Master",
          icon: '<i class="devicon-mysql-plain"></i>',
          logo: "assets/logo/MySQL.svg",
        },
        {
          name: "Serverless Framework",
          level: "Master",
          icon: '<i class="devicon-mysql-plain"></i>',
          logo: "assets/logo/MySQL.svg",
        },
      ],
    },
    {
      category: "Tools & Other Technologies",
      keywords: [
        {
          name: "AWS",
          level: "Master",
          icon: '<i class="devicon-amazonwebservices-plain"></i>',
          logo: "assets/logo/Aws.svg",
        },
        {
          name: "GCP",
          level: "Master",
          icon: '<i class="devicon-googlecloud-plain"></i>',
          logo: "assets/logo/Google-Cloud.svg",
        },
        {
          name: "Firebase",
          level: "Master",
          icon: '<i class="devicon-firebase-plain"></i>',
          logo: "assets/logo/Firebase.svg",
        },
        {
          name: "Git && SVN",
          level: "Master",
          icon: '<i class="devicon-firebase-plain"></i>',
          logo: "assets/logo/Firebase.svg",
        },
        {
          name: "Webpack",
          level: "Master",
          icon: '<i class="devicon-firebase-plain"></i>',
          logo: "assets/logo/Firebase.svg",
        },
        {
          name: "npm && Yarn",
          level: "Master",
          icon: '<i class="devicon-firebase-plain"></i>',
          logo: "assets/logo/Firebase.svg",
        },
        {
          name: "VSCode",
          level: "Master",
          icon: '<i class="devicon-firebase-plain"></i>',
          logo: "assets/logo/Firebase.svg",
        },
        {
          name: "Adobe Illustrator",
          level: "Master",
          icon: '<i class="devicon-firebase-plain"></i>',
          logo: "assets/logo/Firebase.svg",
        },
        {
          name: "Figma",
          level: "Master",
          icon: '<i class="devicon-firebase-plain"></i>',
          logo: "assets/logo/Firebase.svg",
        },
      ],
    },
  ],
  languages: [
    {
      language: "English",
      fluency: "Full Professional Proficiency",
    },
    {
      language: "Tamil",
      fluency: "Full Professional Proficiency",
    },
    {
      language: "Malayalam",
      fluency: "Elementary Proficiency",
    },
  ],
  interests: [
    "Mobile Application",
    "Music",
    "Programming",
    "Social Service",
    "Sports",
    "Web Development",
    "Technology",
    "Gadgets",
    "Learning",
    "Data Analysis",
    "AI/ML/DS",
  ],
  references: [
    {
      name: "Jane Doe",
      reference: "Reference...",
    },
  ],
};

export { akashpreet as default };
